### ISSUE TITLE
plotVaf NA removal not working

### ISSUE THREAD

**Issue by t-neumann** [PoisonAlien/maftools#311]
Hi,

when I try to call the `plotVaf` function like this:

```
plotVaf(maf = MCC, vafCol = 'VAF')
```

I get the following error:

```
Error in .checkTypos(e, names(x)) : 
  Object 'value' not found amongst Hugo_Symbol, t_vaf
```

I think it's a problem of the following line, since `value` is never defined anywhere?

https://github.com/PoisonAlien/maftools/blob/0aa9002b92a11690f55f6cddee8dea271eb096ba/R/plot_vaf.R#L54

At least up until then, the function is working for me:

```
suppressWarnings(datm <- data.table::melt(data = dat.genes[, 
        .(Hugo_Symbol, t_vaf)]))

datm

> datm
      Hugo_Symbol  t_vaf
   1:        MUC6 0.0059
   2:        MUC6 0.0005
   3:        MUC6 0.0002
   4:        MUC6 0.0002
   5:        MUC6 0.0003
  ---                   
1051:       MUC16 0.0000
1052:       MUC16 0.0000
1053:       HLA-B 0.0000
1054:       HLA-B 0.0000
1055:       HLA-B 0.0000

> datm = datm[!is.na(value)]
Error in .checkTypos(e, names(x)) : 
  Object 'value' not found amongst Hugo_Symbol, t_vaf
```

**Comment by PoisonAlien** [comment]
Hello,
I believe it's the way data.table names its measured values. I think I have fixed it. Could you try and let me know if its helps? You will have to install from GitHub.
Thanks.

**Comment by t-neumann** [comment]
Hi,

I tested it and it seems there's still a problem that when subsetting the MAF object into a dataframe, the VAF column is interpreted as character and than the subsequent processing crashes:

```
datm = datm[!is.na(value)]
> datm
     Hugo_Symbol variable   value
  1:       IGFN1    t_vaf 14.9016
  2:      AHNAK2    t_vaf 19.6654
  3:        MUC4    t_vaf 29.3009
  4:        MUC4    t_vaf 14.9343
  5:        MUC4    t_vaf 10.3207
 ---                             
244:       PLIN4    t_vaf  30.496
245:        MUC4    t_vaf 15.0931
246:        MUC4    t_vaf 16.7556
247:       HLA-A    t_vaf 14.3043
248:      MAGEC1    t_vaf 16.6467
> max(datm$value, na.rm = TRUE) > 1
[1] TRUE
> datm$value/100
Error in datm$value/100 : non-numeric argument to binary operator
> datm$value
  [1] "14.9016" "19.6654" "29.3009" "14.9343" "10.3207" "14.398"  "40.3834" "42.5977" "45.7619" "27.6689" "18.0719" "13.7246" "20.6213"
 [14] "43.0806" "12.0649" "33.1065" "13.2744" "18.1182" "11.1303" "12.695"  "11.5405" "14.5793" "11.6412" "18.9184" "15.1979" "15.6544"
 [27] "19.5211" "11.9922" "18.4527" "16.036"  "20.7322" "20.5969" "16.7668" "13.8303" "16.9346" "39.2133" "47.1137" "12.615"  "29.5746"
 [40] "10.7444" "10.6303" "22.5909" "20.8483" "19.2174" "17.5222" "19.1268" "16.4415" "22.2675" "11.5137" "19.2658" "12.4808" "11.2752"
 [53] "15.5931" "13.8608" "12.4062" "18.0983" "24.6637" "13.2656" "14.1095" "14.007"  "16.8187" "20.1814" "21.9227" "18.1553" "18.4042"
 [66] "10.7753" "19.1678" "52.4701" "10.3355" "12.9351" "14.0331" "17.981"  "13.4826" "17.2771" "16.589"  "10.4688" "17.6458" "18.7131"
 [79] "11.0942" "10.6912" "11.0164" "22.1007" "19.649"  "19.5621" "25.9931" "10.6698" "21.5061" "13.676"  "19.4857" "25.5999" "30.2496"
 [92] "16.5811" "20.4534" "17.1826" "13.2108" "10.2878" "26.6864" "10.1134" "20.3169" "23.1017" "26.0007" "20.6087" "11.9033" "14.9025"
[105] "14.3958" "13.1931" "17.2749" "12.0716" "16.3666" "11.8699" "13.6735" "17.503"  "11.2957" "12.66"   "38.1937" "43.4769" "26.6969"
[118] "12.4727" "22.7776" "41.7937" "23.1885" "13.5977" "20.2102" "33.6855" "11.206"  "19.3936" "10.0739" "17.8291" "29.6413" "31.3533"
[131] "17.5086" "10.0608" "11.621"  "21.1771" "11.1573" "12.1143" "21.8903" "24.4662" "15.6772" "22.9617" "10.7564" "18.2387" "12.0069"
[144] "17.1334" "12.7658" "17.3528" "11.2173" "10.0044" "13.7369" "22.044"  "11.0844" "15.1515" "12.617"  "14.8992" "13.4047" "14.4088"
[157] "35.5817" "24.2421" "21.6767" "37.9974" "25.545"  "23.1768" "20.4053" "17.5666" "14.0888" "17.5613" "23.13"   "15.2776" "30.1421"
[170] "23.085"  "14.5875" "35.4087" "10.6405" "24.9802" "10.1658" "13.627"  "13.8057" "18.1093" "10.2321" "11.1483" "10.9091" "12.3677"
[183] "14.3116" "15.7255" "12.949"  "12.9751" "19.3795" "21.7672" "29.1726" "12.4552" "13.0651" "23.091"  "19.0472" "11.6923" "12.8126"
[196] "10.4471" "20.1185" "15.832"  "17.1156" "12.5714" "15.3849" "10.3382" "17.4014" "13.4526" "13.8409" "29.7432" "10.7072" "44.0727"
[209] "13.4348" "11.7613" "12.351"  "18.7338" "38.4994" "37.2085" "24.24"   "24.9464" "25.4518" "21.5918" "12.8612" "12.0471" "10.2955"
[222] "13.8525" "25.4043" "22.6269" "36.1644" "43.1949" "12.2177" "16.6405" "36.3796" "15.0061" "18.7192" "29.4272" "17.4341" "11.5118"
[235] "29.8497" "14.6907" "33.8103" "15.9229" "11.4957" "12.1175" "14.7496" "22.4663" "15.2326" "30.496"  "15.0931" "16.7556" "14.3043"
[248] "16.6467"
```

Probably this should fix it:

```
datm$value = as.numeric(datm$value)/100
```

**Comment by PoisonAlien** [comment]
Hi,
Sorry for late reply. Yes you're correct. By default data.table should read that column as a numeric, but don't know how it missed it.
Did you generate the maf object with `read.maf`?

**Comment by t-neumann** [comment]
No that is actually generated via `annovarToMaf`.

**Comment by PoisonAlien** [comment]
Ah, I see. Anyway I have made the changes. Please do try and let me know if you still have the issue.
