### ISSUE TITLE
Size of blocks for clinical data and sample labels in oncoplot

### ISSUE THREAD

**Issue by Martulie** [PoisonAlien/maftools#512]
Hello, 
I have a problem when creating maftools oncoplot enriched for clinical data. In the code, there is probably the size of whole clinicalFeatures block set by some strict number so when I add more than 2 features, the output becomes too small and unreadable. I went through the code here on github, and I found argument anno_height which I think might deal with that problem and allow me to set the high manually, but when I use it, I get error unused argument (anno_height = 5). packageVersion("maftools") gives ‘2.2.10’ and I installed it by both "maftools" as is on web page and by "PoisonAlien/maftools" as is recommended here. I have the same problem with sample labels - the size of block for sample names is too small and it is possible to see only parts of names in the picture. Can you please advice me on how to make it right? I tried to find scripts in installed packages in my computer and to change it there but I didn't find the same ones as you have here. I am very new in R so I hope this is not any greenhorn question, I will be really happy for some advice.

**Comment by PoisonAlien** [comment]
Hello,
No problem, please feel free to ask or report bugs/errors. Some of the updates made to the package are not available on Bioconductor yet, so some of the options are available on GitHub only. Make sure you have installed it from GitHub.

```r
BiocManager::install(pkgs = "poisonalien/maftools")
```

To increase the annotation height set `anno_height` to larger number (default is 1), and to accommodate sample labels set `barcode_mar` (Default is set to 4). 
Unused argument error suggests that you're still running the older version. Install from GitHub and restart the session and it should work fine.

**Comment by Martulie** [comment]
Amazing, now it all works :) 
The last problem is that legend is out of the width of PDF and when I enlarge the width of PDF, it deforms the graph. Is it possible to sort a legend to particular clinical data vertically?

**Comment by PoisonAlien** [comment]
Legends are always tricky with base graphics. I have pushed some minor fixes which should mitigate the issue. Could you try it again? You will have to reinstall from github.

**Comment by Martulie** [comment]
Hello, thank you very much!
I deleted the maftools library and installed it again and I still can't see the whole legend, despite I lowered the amount of clinical features to 4, it still sorts it next to each other. But I have some problems with updating Lattice, Matrix and Survival. Can it influence the problem?

**Comment by PoisonAlien** [comment]
No Lattice, Matrix and Survival shouldn't be any issue. Unfortunately the function doesn't handle legends very well :|
One thing you could try is to save the image to a large a pdf.

```r
pdf(file = "plot.pdf", width = 12, height = 10, paper = "special", bg = "white")
oncoplot(...)
dev.off()
```

**Comment by Martulie** [comment]
Nope, but no worries, I'll handle it by Inkscape. Maftools has helped me a lot anyway, thanks for that! :) 

Have a nice day,
Martina

**Comment by clersdom** [comment]
Hi @PoisonAlien 

Is there anything similar to `anno_height` for `gisticOncoPlot`? 
I would like to align an oncoplot and a gisticplot for the same samples but the sizes of the cells for each gene and cytoband altered appear with different sizes, respectively.

Thanks!
