### ISSUE TITLE
Copy number labels and coloring in coBarPlot

### ISSUE THREAD

**Issue by Pax2NT** [PoisonAlien/maftools#609]
Hello,
Many thanks for developing this tool! I am trying to plot 2 cohorts via coBarPlot, and the copy number alterations (imported via cnTable) are displayed in the chart as white boxes without labels in the figure legend. The displayed percentages are correct, but is there a way to fix this display?

**Comment by PoisonAlien** [comment]
Hi,
Yes, you are correct and, I am able to reproduce the issue. Its a bug and I will fix it soon.

**Comment by PoisonAlien** [comment]
Hi,
Thanks for reporting. I have fixed it. Please let me know if it works for you. You will have to re-install from GitHub.

P.S: Note that those genes which are CN altered as well as mutated are annotated as `Complex_Event`

**Comment by Pax2NT** [comment]
Many thanks - that does now show the complex_event correctly. I'm still not
getting my copy number labels (in this case "Amplification" and "Deletion")
to populate in the legend or be colored in the chart.

**Comment by PoisonAlien** [comment]
CN status should be `amp` or `del`. Not `Amplification` or `Deletion` since the values are hard coded..
